"""Protocol layer: typed USB/message models, checksum detectors, framing and parsing.

Design rule: **never discard bytes.** Every parsed structure keeps the original
raw bytes, and any byte not explained by a hypothesis stays visible as an
``unknown`` field.
"""
from __future__ import annotations

from .models import (
    AckResponse,
    BulkFrame,
    DeviceInfoResponse,
    Direction,
    ErrorResponse,
    Field,
    InterruptCommand,
    InterruptResponse,
    MessageRole,
    ParsedFrame,
    ProtocolMessage,
    TransferType,
    UsbTransfer,
)
from .verified import (
    BLOCK_READ,
    BULK_BODY_SIZE,
    BULK_READ_MAGIC,
    BULK_TRANSFER_SIZE,
    BULK_WRITE_MAGIC,
    STORAGE_QUERY,
    UPDATE_BLOCK,
    UPDATE_PREPARE,
    BulkReadObservation,
    BulkWriteObservation,
    ObservedRequest,
    ObservedResponse,
    UpdateBlockObservation,
    UpdatePrepareObservation,
    VerifiedRequest,
    VerifiedResponse,
    build_block_read,
    build_storage_query,
    classify_bulk_in,
    inspect_bulk_read,
    inspect_bulk_write,
    parse_observed_request,
    parse_observed_response,
    parse_request,
    parse_response,
    parse_update_block,
    parse_update_prepare,
    reassemble_bulk_read_fragments,
)

__all__ = [
    "Direction",
    "TransferType",
    "UsbTransfer",
    "Field",
    "ParsedFrame",
    "MessageRole",
    "ProtocolMessage",
    "InterruptCommand",
    "InterruptResponse",
    "BulkFrame",
    "AckResponse",
    "ErrorResponse",
    "DeviceInfoResponse",
    "STORAGE_QUERY",
    "BLOCK_READ",
    "UPDATE_PREPARE",
    "UPDATE_BLOCK",
    "BULK_TRANSFER_SIZE",
    "BULK_BODY_SIZE",
    "BULK_READ_MAGIC",
    "BULK_WRITE_MAGIC",
    "VerifiedRequest",
    "VerifiedResponse",
    "ObservedRequest",
    "ObservedResponse",
    "BulkWriteObservation",
    "BulkReadObservation",
    "UpdatePrepareObservation",
    "UpdateBlockObservation",
    "build_storage_query",
    "build_block_read",
    "parse_request",
    "parse_observed_request",
    "parse_observed_response",
    "parse_response",
    "parse_update_prepare",
    "parse_update_block",
    "classify_bulk_in",
    "inspect_bulk_write",
    "inspect_bulk_read",
    "reassemble_bulk_read_fragments",
]
